// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prjMaestroDetalle.Models;

namespace prjMaestroDetalle.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("prjMaestroDetalle.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Articulo");
                });

            modelBuilder.Entity("prjMaestroDetalle.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("prjMaestroDetalle.Models.CondicionPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("CondicionPago");
                });

            modelBuilder.Entity("prjMaestroDetalle.Models.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<double>("ITBIs");

                    b.Property<int>("IdArticulo");

                    b.Property<int>("IdFactura");

                    b.Property<double>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdFactura");

                    b.ToTable("DetalleFactura");
                });

            modelBuilder.Entity("prjMaestroDetalle.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("prjMaestroDetalle.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadArticulo");

                    b.Property<string>("Comentario")
                        .HasMaxLength(60);

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("IdCliente");

                    b.Property<int>("IdCondicionPago");

                    b.Property<int>("IdEstado");

                    b.Property<double>("SubTotal");

                    b.Property<double>("Total");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdCondicionPago");

                    b.HasIndex("IdEstado");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("prjMaestroDetalle.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Existencia");

                    b.Property<double>("ITBIs");

                    b.Property<int>("IdArticulo");

                    b.Property<double>("PrecioCompra");

                    b.Property<double>("PrecioVenta");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("prjMaestroDetalle.Models.DetalleFactura", b =>
                {
                    b.HasOne("prjMaestroDetalle.Models.Articulo", "Articulo")
                        .WithMany("DetalleFactura")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("prjMaestroDetalle.Models.Factura", "Factura")
                        .WithMany("DetalleFactura")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("prjMaestroDetalle.Models.Factura", b =>
                {
                    b.HasOne("prjMaestroDetalle.Models.Cliente", "cliente")
                        .WithMany("Factura")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("prjMaestroDetalle.Models.CondicionPago", "CondicionPago")
                        .WithMany("Factura")
                        .HasForeignKey("IdCondicionPago")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("prjMaestroDetalle.Models.Estado", "Estado")
                        .WithMany("Factura")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("prjMaestroDetalle.Models.Inventario", b =>
                {
                    b.HasOne("prjMaestroDetalle.Models.Articulo", "Articulo")
                        .WithMany("Inventario")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
